import './globals.css';
import type { Metadata } from 'next';
import RootLayoutCtn from '@/layouts/RootLayout';
import AppProviders from './app-providers';
import 'react-quill/dist/quill.snow.css';

export const metadata: Metadata = {
    title: 'Ecommerce',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <RootLayoutCtn>
            <AppProviders>{children}</AppProviders>
        </RootLayoutCtn>
    );
}
