import './globals.css';
import type { Metadata } from 'next';
import RootLayoutCtn from '@/layouts/RootLayout';
import AppProviders from './app-providers';

export const metadata: Metadata = {
    title: 'Nov store',
    description: 'Generated by Raven Le',
    colorScheme: 'light',
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <RootLayoutCtn>
            <AppProviders>{children}</AppProviders>
        </RootLayoutCtn>
    );
}
