import './globals.css';
import type { Metadata } from 'next';
import RootLayoutCtn from '@/layouts/RootLayout';
import AppProviders from './app-providers';
import { Suspense } from 'react';
import Loading from './loading';

export const metadata: Metadata = {
    title: 'Toshiro Ecommerce',
    description: 'Generated by create next app',
};
export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <RootLayoutCtn>
            <AppProviders>
                <Suspense fallback={<Loading />}>{children}</Suspense>
            </AppProviders>
        </RootLayoutCtn>
    );
}
