POST http://localhost:3000/api/products
content-type: application/json

{
  "name": "HAHA ",
  "price":10000,
  "discount":0.1,
  "categoryId":"650734bbe8d61a9af0d4894c",
  "brandId":"65074cab5d1bf28358fe4bc1",
  "description":"description",
  "images":["ákdasdhaksjdhaskjdhas","ádhaskjdhaskjdhaks"],
  "quantity":50,
  "categoryId": "65073fe9007aa481fa819c99",
  "brandId": "65074cbc5d1bf28358fe4bc2",
}

###

PUT http://localhost:3000/api/product/65075afe13be3f532b80a621
content-type: application/json

{
  "name": "iPHONE12",
  "price": 123123123,
  "discount": 0.1,
  "description": "<p>EDIT</p>",
  "images": [
        "https://firebasestorage.googleapis.com/v0/b/ecommerce-next-app-9482b.appspot.com/o/product%2Fiphone-14-promax-white.png?alt=media&token=cda8630c-e8fe-429c-8f71-1e964c960581"
    ],
  "quantity": 200,
  "categoryId": "65073fe9007aa481fa819c99",
  "brandId": "65074cbc5d1bf28358fe4bc2",
}
